### ISSUE TITLE
How to restore the archived notebook

### ISSUE THREAD

**Issue by yuanjie-ai** [jvn-io/jovian-support#6]
How to restore the archived notebook? 
I canot find it

**Comment by aakashns** [comment]
Hi @Jie-Yuan,
Thanks for posting the issue. We are working on adding an 'Archived' tab on the profile page. It will be live by Friday.

If you are facing any other issues, please let us know and we'll be happy to help you.

**Comment by aakashns** [comment]
Hi @Jie-Yuan,
I'm glad to inform you that the Archived notebooks features has been deployed. You can now visit your profile, and you will se an "Archived" tab showing archived notebooks.
